# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixVectorMult <- function(mat, vec) {
    .Call(`_MVMRPRESS_matrixVectorMult`, mat, vec)
}

g <- function(theta, A, b) {
    .Call(`_MVMRPRESS_g`, theta, A, b)
}

Gr <- function(theta, A, b, tt, lambda) {
    .Call(`_MVMRPRESS_Gr`, theta, A, b, tt, lambda)
}

PGD <- function(A, b, theta, lambda, iter = 1000L) {
    .Call(`_MVMRPRESS_PGD`, A, b, theta, lambda, iter)
}

rcpp_hello_world <- function() {
    .Call(`_MVMRPRESS_rcpp_hello_world`)
}

